<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Orange Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>eeaf4615-7e86-46af-ae26-018e13d6f589</testSuiteGuid>
   <testCaseLink>
      <guid>e1205d07-1df7-4507-8708-1b1ef7e82e41</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Error_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da6520d6-e6e9-4aa8-a6b4-8f1b3c9ca1c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bc2dd42-3d32-4b1f-b35c-51f4c120514f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60ef64af-2e22-422d-a2db-10ec2cf240be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98d770c5-ead1-4f87-8f23-f8e87add8231</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d44ded6-4833-41c4-8730-7af34d873e3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>cb864e3c-4746-4c30-9951-ffc0046463b7</id>
         <masked>false</masked>
         <name>firstName</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>24e9f734-de6b-4d61-84c0-923105e545c3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28175865-2013-4cad-9f70-85946f7f3090</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50564aa0-4746-46a0-a2be-62b73d9085f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94997756-07c4-47b7-bd32-1ad22c56c33c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>24e9f734-de6b-4d61-84c0-923105e545c3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>﻿firstName</value>
         <variableId>cb864e3c-4746-4c30-9951-ffc0046463b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>24e9f734-de6b-4d61-84c0-923105e545c3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>midleName</value>
         <variableId>a1850953-915d-4aad-a2ac-cee2db115db3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>24e9f734-de6b-4d61-84c0-923105e545c3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>fc0d1f94-6c08-48df-bb31-508bafea25e3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
